echimp_gitops:
  environment: prod
  project: echimp
  repoURL: https://github.com/martinmlouis/github_builds.git
  name: nginx-github
  destinationCluster: https://kubernetes.default.svc
  namespace: argo-cd
  targetRevision: 1.1.1
  path: charts
echimp_helmops:
  environment: prod
  project: echimp
  repoURL: http://chartmuseum.35.212.92.161.nip.io
  name: nginx
  destinationCluster: https://kubernetes.default.svc
  namespace: argo-cd
  targetRevision: 1.1.1    
