---        
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namesapce: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/martinmlouis/echimp.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true

