---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echimp-github
  namespace: argo-cd
spec:
  generators:
  - list:
      elements:
      - destinationCluster: https://kubernetes.default.svc
        environment: dev
        name: nginx-github
        namespace: argo-cd
        path: charts
        project: echimp
        repoURL: https://github.com/martinmlouis/github_builds.git
        targetRevision: 0.1.0
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        Environment: '{{.environment}}'
        GithubChartVersion: '{{.targetRevision}}'
      name: '{{.name}}'
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: '{{.destinationCluster}}'
      project: '{{.project}}'
      source:
        helm:
          valueFiles:
          - '{{.environment}}-values.yaml'
        path: '{{.path}}/{{.targetRevision}}'
        repoURL: '{{.repoURL}}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
