apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx3
  namespace: default
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc    
  template:      
    metadata:
      name: nginx3
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: http://chartmuseum.35.212.92.161.nip.io
        targetRevision: 1.1.1
        helm:
          valueFiles:
          - dev-values.yaml
        chart: nginx
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: default

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
          - Prune=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
